all:
  children:
    local:
      hosts:
        localhost:
          ansible_connection: local
    control:
      hosts:
        skdsrv01
      vars:
        http_port: 80
    workers:
      hosts:
        skdsrv02
